config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :questions, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :answers, only: [:create] 
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  with_options presence: true do
    validates :name
    validates :content
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates_uniqueness_of :question_id, scope: :user_id
end

app/models/question.rb
class Question < ApplicationRecord 
  belongs_to :user
  has_many :answers
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/models/question_form.rb
class QuestionForm
  include ActiveModel::Model
  attr_accessor :title, :content, :name, :user_id, :id, :created_at, :updated_at, :video, :youtube_url

  with_options presence: true do
    validates :name
    validates :content
    validates :title
  end

  def move
    mount_uploader :video, VideoUploader
  end
  
  def save
    question = Question.create(title: title, content: content, name: name, user_id: user_id, video: video, youtube_url: youtube_url)
  end

  def update(params, question)
    question.update(params)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には半角の英字数字の両方を含めて設定してください'
  
  validates :nickname, presence: true
    
  has_many :questions
  has_many :likes, dependent: :destroy
  has_many :liked_questions, through: :likes, source: :question

  def already_liked?(question)
    self.likes.exists?(question_id: question.id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    Answer.create(answer_params)
    redirect_to question_path(params[:question_id])
  end

  private
  def answer_params
    params.require(:answer).permit(:content, :name).merge(question_id: params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
      
  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(question_id: params[:question_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(question_id: params[:question_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!,  except: [:index]
  before_action :set_question, only: [:show, :edit, :update]

  def index
    @questions = Question.all
    @questions = Question.all.page(params[:page]).per(7)
  end

  def new
    @question_form = QuestionForm.new
  end

  def create
    @question_form = QuestionForm.new(question_form_params)
    @question_form.user_id = current_user.id
    url = params[:question_form][:youtube_url]
    url = url.last(11)
    @question_form.youtube_url = url
    respond_to do |format|
      if @question_form.valid?
        @question_form.save
        format.html { redirect_to root_path, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question_form }
      else
        format.html { render :new }
        format.json { render json: @question_form.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show 
    @answer = Answer.new
    @answers = @question.answers
    @like = Like.new
  end

  def edit
    question_attributes = @question.attributes
    @question_form = QuestionForm.new(question_attributes)
  end

  def update
    @question_form = QuestionForm.new(question_form_params)
    url = params[:question_form][:youtube_url]
    url = url.last(11)
    @question_form.youtube_url = url
    respond_to do |format|
      if @question_form.valid?
        @question_form.update(question_form_params, @question)
        format.html { redirect_to root_path, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question_form }
     else
        format.html { render :edit }
        format.json { render json: @question_form.errors, status: :unprocessable_entity }
     end
    end
  end

  def destroy
    if @question = Question.find(params[:id])
      @question.destroy
    end 
      redirect_to root_path
  end

  def search
    if params[:q]&.dig(:title)
      squished_keywords = params[:q][:title].squish
      params[:q][:title_cont_any] = squished_keywords.split(" ")
    end
    @q = Question.ransack(params[:q])
    @questions = @q.result.page(params[:page]).per(7)
  end
  
  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_form_params
    params.require(:question_form).permit(:title, :content, :name, :video, :youtube_url).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "uri"
  def text_url_to_link text
    URI.extract(text, ['http','https']).uniq.each do |url|
      sub_text = ""
      sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"
      text.gsub!(url, sub_text)
    end
    return text
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">   
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: @question_form, url: url, method: method, id: 'new_question', local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <div class='input-items'>
    <div class='input-youtube'>
      <%= f.text_field :youtube_url, placeholder: "youtube URL ※埋め込み用コードを使用下さい" %>
    </div>
    <div class="img-upload">
      <div class="weight-bold-text">動画(※youtube除く)</div>
      <div class="click-upload">
        <%= f.file_field :video, :accept => 'video/*' %>
      </div>
    </div>
    <div class='input-items__title'>
      <%= f.text_field :title, placeholder: "タイトル" %>
    </div>
    <div class='input-items__content'>
      <%= f.text_area :content, placeholder: "投稿内容" %>
    </div>
    <div class='input-items__name'>
      <%= f.text_field :name, placeholder: "投稿者名" %>
    </div>
    <div class='input-items__submit'>
      <%= f.submit 'POST'%>
    </div>
  </div>
<% end %>

app/views/questions/edit.html.erb
<%= render "shared/header" %>

<div class='new-main'>
  <%# フォーム %>
  <div class='form'>
    <%# フォームのヘッダー表示 %>
    <div class='form-top'>投稿画面</div>

    <%# フォームのメイン部分 %>
    <div class='form-main'>
      <%= render partial: 'form', locals: {url: question_path(@question.id), method: :patch} %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/questions/index.html.erb
<%# 一覧表示画面 %>
<%= render "shared/header" %>

<div class='index-main'>
  <div class='post-contents'>
    <% @questions.each do |question| %>
      <%# 投稿１件分の表示 %>
      <div class='post-content'>
        <%# コメントに関する表示 %>
        <div class='comment'>
          <div class='comment__num'>
             <%= question.liked_users.count %>
          </div>
          <div class='comment__unit'>
            Good!
          </div>
        </div>

        <%# 質問本文の表示 %>
        <div class='question'>
          <div class='question-top'>
            <div class='question-top__title'>
              <%= link_to question.title, question_path(question.id) %>
            </div>
            <div class='question-top__name'>
              <%= question.name %>
            </div>
          </div>
          <div class='question-bottom'>
            <div class='question-bottom__content'>
              <%= question.content %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="page-view">
   <%= paginate @questions %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/questions/new.html.erb
<%= render "shared/header" %>

<div class='new-main'>
  <%# フォーム %>
  <div class='form'>
    <%# フォームのヘッダー表示 %>
    <div class='form-top'>投稿画面</div>

    <%# フォームのメイン部分 %>
    <div class='form-main'>
      <%= render partial: 'form', locals: {url: questions_path, method: :post} %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/questions/search.html.erb
<%= render "shared/header" %>

<div class='index-main'>
  <div class='post-contents'>
    <% @questions.each do |question| %>
      <%# 投稿１件分の表示 %>
      <div class='post-content'>
        <%# コメントに関する表示 %>
        <div class='comment'>
          <div class='comment__num'>
            <%= question.liked_users.count %>
          </div>
          <div class='comment__unit'>
            Good!
          </div>
        </div>

        <%# 質問本文の表示 %>
        <div class='question'>
          <div class='question-top'>
            <div class='question-top__title'>
              <%= link_to question.title, question_path(question.id) %>
            </div>
            <div class='question-top__name'>
              <%= question.name %>
            </div>
          </div>
          <div class='question-bottom'>
            <div class='question-bottom__content'>
              <%= question.content %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="page-view">
   <%= paginate @questions %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/questions/show.html.erb
<%= render "shared/header" %>

<div class="show-main">
  <div class="show-contents">
    <%# 質問内容の表示 %>
    <div class="show-question">
      <div class="show-question__title">
        <%= @question.title %>
      </div>
      <div class="question-youtube-content">
        <% if @question.youtube_url != "" %>
         <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @question.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <% end %>
      </div>
       <div class="question-img-content">
        <% if @question.video != nil %>
          <%= video_tag @question.video.url, autoplay: false, muted: false, controls: true , :size => "30x40"%>
        <% end %>
      </div>
      <div class="show-question__content">
        <%= text_url_to_link((h(@question.content).html_safe)).html_safe %>
      </div>
      <div class="show-question__name">
        <%= @question.name %>
      </div>

      <div class="good-times">Good! <%= @question.likes.count %></div>
        <% if current_user.already_liked?(@question) %>
          <%= button_to '取消', question_like_path(@question), method: :delete %>
        <% else %>
          <%= button_to 'Good!', question_likes_path(@question) %>
        <% end %>
      </div>
      
      <%# 回答投稿フォームの表示 %>
      <div class="show-answer-form">
        <%= form_with(model: [@question, @answer], url: question_answers_path(@question.id), method: :post, local: true) do |form| %>
        <div class="show-answer-form__heading">
          回答する
        </div>
        <div class="show-answer-form__content">
          <%= form.text_area :content, placeholder: "回答する", rows: "4" %>
        </div>
        <div class="show-answer-form__name">
          <%= form.text_field :name, placeholder: "投稿者名" %>
        </div>
        <div class="show-answer-form__submit">
          <%= form.submit "POST" %>
        </div>
        <% end %>     
      </div>

      <div class="show-edit-form">
       <% if current_user.id == @question.user_id %>
        <%= link_to "編集", edit_question_path(@question.id) , method: :get, class: "question-red-btn" %>
        <%= link_to "削除", question_path(@question.id), method: :delete, class:"question-destroy" %>
       <% end %>
      </div>

      <%# 回答一覧の表示 %>
      <div class="show-answers">
        <div class="answers-heading">
          いままでの回答：
        </div>
        <% @answers.each do |answer| %>
          <div class="answer-content">
            <div class="answer-content__text">
              <%= text_url_to_link((h(answer.content).html_safe)).html_safe %>
            </div>
            <div class="answer-content__name">
              <%= answer.name %>
            </div>
          </div>
        <% end %>
      </div>
    </div>  
  </div>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <div class="foot-wrap">
        <div class="menu-left">
            <h3>規約</h3>
            <ul class="foot-left">
                <li><a href="#">利用規約</a></li>
                <li><a href="#">ヘルプ</a></li>
                <li><a href="#">About</a></li>
            </ul>
        </div>
        <div class="menu-center">
            <h3>content</h3>
            <ul class="foot-center">
                <li><a href="#">募集</a></li>
                <li><a href="#">リリースノート</a></li>
                <li><a href="#">API</a></li>
            </ul>
        </div>
        <div class="menu-right">
            <h3>SNS</h3>
            <ul class="foot-right">
                <li><a href="#">公式</a></li>
                <li><a href="#">関連</a></li>
                <li><a href="#">運営</a></li>
            </ul>
        </div>
        <small class="cmark">©️copyright 2022
            <a href="#">sample-site.</a>
        </small>
    </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class='header-contents'>
    <div class='logo'>
      <%= link_to 'B忘6', root_path %>
    </div>
      <ul class="nav-list">
        <li class="nav-list-item">
          <a href="#">Home</a>
        </li>
        <li class="nav-list-item"><a href="#">category</a></li>
        <li class="nav-list-item"><a href="#">rank</a></li>
      </ul>
    <div class='search-bar-contents'>
      <%= search_form_for Question.ransack(params[:q]), url: search_questions_path, html: {class: "search-form"} do |f| %>
        <%= f.text_field :title, placeholder: '投稿から探す', class: 'input-box' %>
        <%= f.label :submit, class: "search-button" do %>
        <input type="submit" value="検索" class="send">
        <%= f.submit :submit, id: "q_submit", style: "display: none;"%>
        <% end %>
      <% end %>
    </div>

    <div class='post-button'>
      <% if user_signed_in? %>
        <%= link_to '投稿', new_question_path, class: "shitumon" %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
      <% else %>
        <%= link_to 'ログイン', new_user_session_path, class: "login" %>
        <%= link_to '新規登録', new_user_registration_path, class: "sign-up" %>
      <% end %>
    </div>
  </div>
</header>